title: 신혜원의 포트폴리오 사이트
name: 신혜원
email: shin4821@naver.com
description: >-
  Software Engineer


baseurl: ""
url: https://HyeWon4821.github.io


# profile 이미지
profile_image: images/companyPicture2.jpg


# SNS 아이디
facebook_id: #
instagram_id: #


# Youtube vid
youtube_vid: #


# Custom Color
primary: 2c98f0 #b72cf0
primary_hover: 44A4F2 #9a2dc7
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
#slider_0: # 형식에 맞추어 항목 추가
#- background_url: images/cover_bg_2.jpeg
#  title: 안녕하세요. <br>반갑습니다!</br>


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/cover_bg_2.jpg
  title: HyeWon<br>portfoilo<br>site
  subtitle: >- 
    조금은 늦었지만<br>
    무작정 따라하며 성장해온<br>
    초보 개발자 신혜원의<br>
    포트폴리오 사이트 입니다.
  #position: absolute
  #transform: translate ( -50%, -50%)
  #left: 180px
  #bottom: 50px


# About
about_meta: About Me
about_header: >- 
  "중어중문학과 출신 초보 개발자"
about_introduce: >-
  "안녕하세요. 소프트웨어 개발 전문가를 꿈꾸는 신혜원 입니다."
about_content: >-
  학창 시절부터 무엇인가에 도전하는 삶을 꿈꿔왔습니다. <br>
  나의 능력을 향상시켜 남들에게 인정받는것을 좋아했습니다. <br>
  외국어가 좋아 중어중문학과로 진학하였습니다. 
  진학 당시 중국어를 한마디도 못하는 대학생이었으나 실력을 갈고 닦은 결과,
  교환학생 당시 500명의 중국인을 앞에서 한중말하기대회에 참여하여 수상하기도 하였습니다. <br>
  전공을 살려 들어간 무역회사에서 2년간 열심히 일을 하였습니다. <br>
  하는 일이 싫지 않았지만, 도전을 좋아하는 저에게 있어서 매번 2% 부족한 느낌을 지울 수 없었습니다. <br><br>
  
  우연히 인공지능, 3D 프린터에 관한 책을 읽으면서 프로그래밍에 관심이 갔습니다.
  어떠한 대규모 자본없이 프로그래밍 실력만으로 앱, 프로그램들을 만들어 수익을 창출할 수 있다는 것이,
  내 아이디어만 있으면 그 아이디어를 가장 쉽게 구현할 수 있는 도구가 있다는 것이 너무나 저를 설레게 하였습니다. <br>
  고민은 깊게 판단은 확실하게 하기 위해 저는 퇴사를 하고 프로그래밍 학원을 등록하였습니다. <br>
  전공자도 아니었고 아직도 모르는것 투성이지만 조금 늦은만큼 더 열심히 배워가고 있습니다. <br><br>
  <strong> 또 한번, 저만의 도전이 시작되었습니다. </strong>
about_services: # 형식에 맞추어 항목 추가
- icon: icon-data
  name: MySQL
- icon: icon-monitor
  name: C#/WPF
- icon: icon-code
  name: C++/C
- icon: icon-document-text
  name: MFC/API

about_box_content: >-
   프로그래밍을 공부하며 제일 중요하다고 생각되는 부분은 "문제해결능력"이었습니다.<br>
   탄탄한 로직이 세워지면, 그 후 어떤 언어를 사용하던 언어는 로직을 구현해주는 수단에 지나지 않았습니다. <br>
   저는 "문제해결능력"을 기르기 위하여 배열, 연결리스트, 이분검색트리 라이브러리를 직접 만들어 원리를 익혔습니다. <br>
   또한 C,C++로 기초를 세워 JAVA, C#등 다른 객체지향 언어에 쉽게 접근하고 익힐 수 있는 능력을 길렀습니다. <br>
#  "나는 항상 내가 할 수 없는 일들을 하려 해왔다. <br>
#   나는 내가 할 수 없는 일들을 이루는 방법을 순서대로 적절하게 배우면 그 일들을 이룰 수 있었다. <br>
#   행동은 모든 성공의 기본 열쇠이다."<br>
#    - 파블로 피카소

about_box_button:
   link: https://github.com/shin4821
   name: 행동으로 보여드리겠습니다.



# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 현재 이것을 할 수 있습니다.
tech_content: #
tech_list: # 형식에 맞추어 항목 추가
- name: C/C++
  color: color-1
  animation: fadeInLeft
  percent: 90
  mark: 80
  content: C와 C++ 기초, 데이터 분석과 시각화를 공부하고 C/C++ 언어의 기본적인 문법에 대해 알고 있으며, 자료구조 및 알고리즘을 C/C++로 공부하였습니다.
- name: API/MFC
  color: color-2
  animation: fadeInRight
  percent: 80
  mark: 70
  content: 영문으로 된 API, MFC reference를 보고 직접 인터페이스를 programming 하였습니다. <br><br><br>
- name: MySQL
  color: color-3
  animation: fadeInLeft
  percent: 80
  mark: 70
  content: DBMS중 MySQL을 사용하여 데이터 관리 프로그램을 개발하였습니다.
- name: C#/WPF
  color: color-4
  animation: fadeInRight
  percent: 80
  mark: 70
  content: C#/WPF를 이용하여 게임 런처 프로그램을 개발하였습니다.
tech_desc: #앞으로 연구한것을 서비스화하기 위해서 <strong>javascript, Node JS, 리엑트, 스피링, 헤로쿠, python anywhere 및 아마존 AWS, docker</strong>등을 계속해서 조금씩 공부할 생각입니다. 


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: <span>개인 프로젝트</span><span>팀 프로젝트</span><span>Business</span>
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    # 더보기 내용
project_load_more_url: https://github.com/shin4821

project_my_name: 개인프로젝트(각 항목별 자세한 사항은 detail - github - README를 참고해 주세요)

project_my: # 형식에 맞추어 항목 추가
- background_url: images/notepad.PNG
  animation: fadeInLeft
  name: 메모장 개발<br>(2021.06 ~ 2021.10)<br>사용언어 - C++
  description: 이 메모장은 윈도우 기본 메모장을 참고하여 만든 메모장입니다. 이 메모장을 만들면서 윈도우 메모장에 없어서 아쉬웠던 기능들을 추가하였습니다.
  detail_url: pdf/메모장 프로그램.pdf
  readmore_url: https://github.com/shin4821/NotePad20211130

- background_url: images/accountBook_.PNG
  animation: fadeInLeft
  name: 가계부 개발<br>(2021.05.08 ~ 2021.05.28)<br>사용언어 - C++
  description: 수입, 지출 관리용 가계부를 만들어보았습니다. 시작일자, 종료일자, 적요에 따라 필터링된 수입, 지출, 차액을 볼 수 있습니다.
  detail_url: #
  readmore_url: https://github.com/shin4821/AccountBook20210528

- background_url: images/vocabularyBinder.png
  animation: fadeInLeft
  name: 퀴즈단어장 개발<br>(C++버전 - 2021.05.02 ~ 2021.05.07<br> C버전 - 2021.12.02 ~ 2020.12.16)
  description: 알파벳별로 트리를 만들어 효율적인 단어관리를 할 수 있는 퀴즈 단어장 입니다. 퀴즈를 풀면서 암기 단어, 미암기 단어를 구분하도록 해두어서 효율성을 높혔습니다.
  detail_url: https://github.com/shin4821/IndexBinder-20210517
  readmore_url: https://github.com/shin4821/IndexBinder20210219-

- background_url: images/businessCardBinder.png
  animation: fadeInLeft
  name: 명함철 개발<br>(C++버전 - 2021.03.30 ~ 2021.04.29<br> C버전 - 2020.11.13 ~ 2020.11.25)
  description: 회사별로 트리를 만들어 효율적인 명함관리를 할 수 있는 명함철 입니다. 
  detail_url: https://github.com/shin4821/IndexBinder20210429
  readmore_url: https://github.com/shin4821/IndexBinder20210204-

- background_url: images/vocabulary.png
  animation: fadeInLeft
  name: 단어장 개발<br>(C++버전 - 2021.03.18 ~ 2021.03.30<br> C버전 - 2020.11.10 ~ 2020.11.12)
  description: 기본적인 기능을 갖춘 단어장 입니다. 
  detail_url: https://github.com/shin4821/Vocabulary20210330
  readmore_url: https://github.com/shin4821/Vocabulary20201112

- background_url: images/addressBook.png
  animation: fadeInLeft
  name: 주소록 개발<br>(C++버전 - 2021.02.24 ~ 2021.03.13<br> C버전 - 2020.10.14 ~ 2020.11.10)
  description: 기본적인 기능을 갖춘 주소록 입니다. 
  detail_url: https://github.com/shin4821/AddressBook20210313
  readmore_url: https://github.com/shin4821/AddressBook20201110

#project_team_name: 팀프로젝트
#project_team: # 형식에 맞추어 항목 추가
#- background_url: images/team_project3.PNG
#  animation: fadeInRight
#  name: Anti-Drone_Robot(2020.05)
#  description: 2019년 드론기술발전에 따른 드론관련 사고들이 많아지고 있음을 파악하고 그에따른 대처가 필요하다고 생각 하여 인공지능을 이용한 Anti Drone Robot 을 개발하였다
#  detail_url: #
#  readmore_url: #

#- background_url: images/team_project3.PNG
#  animation: fadeInRight
#  name: sasdasdasdsadsagjghkukt(2020.05)
#  description: 2019년 드론기술발전에 따른 드론관련 사고들이 많아지고 있음을 파악하고 그에따른 대처가 필요하다고 생각 하여 인공지능을 이용한 Anti Drone Robot 을 개발하였다
#  detail_url: #
#  readmore_url: #

#project_business_name: Business
#project_business: # 형식에 맞추어 항목 추가
#- background_url: images/my_business.PNG
#  animation: fadeInTop
#  name: 인프런강의(2021~)
#  description: >-
#    취준과 대학원진학을 동시에 했을때 많은 곳에서 github 주소뿐만아니라 개발 블로그주소도 요청하는데가 많았다.(물론 필수는 아니였지만) 
#  detail_url: #
#  readmore_url: #


# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
exp_content: 현재 개발에는 큰 도움은 되지 않을 수 있지만, 회사에서 필요로 한다면 이런 역량도 가지고 있습니다.
exp_services: # 형식에 맞추어 항목 추가
- name: 외국어능력
  color: color-1
  icon: icon-bulb
  content: 무역회사 재직당시 중국어와 영어로 공급업체와 연락을 취했기에 외국어에 대한 두려움이 없습니다.
- name: 기술습득
  color: color-2
  icon: icon-home
  content: 다양한 영문 reference를 보고 직접 설계에 적용했던 적이 있어, 새로운 기술 역시 잘 받아들일 수 있습니다.
- name: 프로젝트
  color: color-3
  icon: icon-phone3
  content: 다양한 프로젝트를 기획, 진행 해왔기에 업무에 대한 협력과 배분이 익숙합니다. 새로운 프로젝트에 도전적입니다.
exp_counters:
#- name: Online Class Sales
#  count: 344
#  speed: 10000
- name: project
  count: 6
  speed: 3000


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: GXC
  date: 2021.12~2022.02
  content: Native Developer - 게임 런쳐 프로그램 개발  <br> C#, WPF 등을 통해 직접 UI를 제작하고, MVVM 디자인패턴을 이용하여 개발하였습니다.
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft
#- name: 데이터 관리 프로그램(객체지향)
#  date: 2021.02~2021.05
#  content: 주소록, 단어장, 명함철, 퀴즈단어장을 통해 객체지향 데이터 관리 프로그램 제작.  <br> C++, MFC, MySQL, 다양한 자료구조를 통해 설계, 개발하였습니다.
#  color: color-2
#  icon: icon-pen2
#  animation: fadeInRight
#- name: 가계부
#  date: 2021.05~2021.06
#  content: 수입, 지출 관리용 가계부를 만들어보았습니다.  <br> C++, MFC, MySQL, 다양한 자료구조를 통해 설계, 개발하였습니다.
#  color: color-2
#  icon: icon-pen2
#  animation: fadeInRight
#- name: 메모장
#  date: 2021.06~2021.11
#  content: 이 메모장은 윈도우 기본 메모장을 참고하여 만든 메모장입니다.<br>이 메모장을 만들면서 윈도우 메모장에 없어서 아쉬웠던 기능들을 추가하였습니다. <br>객체 설계부터 인터페이스 설계까지 책임지며 약 22,000줄의 큰 프로그램을 다뤄보는 법을 배웠습니다.
#  color: color-2
#  icon: icon-pen2
#  animation: fadeInRight


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: SOFTWARE ENGINEER ACADEMY
  subtitle: 박컴학원 교육생
  date: 2020.07 - 2021.11
  content: 소프트웨어 엔지니어 과정 수료
- title: WPF Masterclass
  date: 2022.01 - 2022.02
  content: Udemy WPF Masterclass 과정 수료
- title: GACHON UNIVERSITY
  subtitle: 가천대학교 중어중문학과 졸업
  date: 2012.03 - 2016.08
  content: 중국 산동대학교 1년 교환학생 
- title: JUNGANG GIRLS HIGH SCHOOL
  subtitle: 중앙여자고등학교
  date: 2009.03 - 2012.02
  content: >-


# Blog
blog_meta: self-improvement
blog_header: BLOG and YOUTUBE
blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
blog_load_more_url: https://shin4821.github.io/
blog_list:
- title: 신혜원의 Dev Blog
  subtitle: 개발 블로그 운영
  date: 2021.11
  content: 시작한지 얼마 되지 않았지만 포기하지않고 어느 한분야라도 '장인'이 되겠다는 마음으로 꾸준히 개발 블로그를 운영해보려고 합니다.
  thumbnail_url: images/gitmain.PNG
  link: https://shin4821.github.io/


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: shin4821@naver.com
  icon: icon-globe-outline
- title: 서울시 종로구
  icon: icon-map
#- title: +82 10 xxxx xxxx
#  icon: icon-phone
- title: 내 Github
  icon: icon-layers2
  url: https://github.com/shin4821
contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)


optional_front_matter:
  remove_originals:    true
